#!/bin/sh -
# Copyright (C) 2010 Red Hat Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

# Calculate the default ELF object architecture for this format.
# There doesn't seem to be an easy way to derive this from binutils,
# so instead we hard code it.

case $(uname -m) in
    i[3456]86) echo "elf32-i386 i386" ;;
    x86_64) echo "elf64-x86-64 i386" ;;
    s390) echo "elf32-s390 s390:31-bit" ;;
    s390x) echo "elf64-s390 s390:31-bit" ;;
    ppc) echo "elf32-powerpc powerpc" ;;
    ppc64) echo "elf64-powerpc powerpc" ;;
    *)
        echo "This architecture is not recognized.  Please update helper/elf-default-arch."
        exit 1
esac
